exports.UPDATE_BUOY = "UPDATE_BUOY";
exports.ADD_BOUNDS = "ADD_BOUNDS";
exports.SOCKET_OPEN = "SOCKET_OPEN";
exports.MAP_RENDER = "MAP_RENDER";
exports.SET_BUOY_FEATURE_MAP = "SET_BUOY_FEATURE_MAP";
exports.UPDATE_BUOY_FEATURE = "UPDATE_BUOY_FEATURE";
